#! /bin/sh

sxhkd &


~/.startscript.sh

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# alt plus mouse to move/resize
bspc config pointer_modifier mod1

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

#bspc monitor --reset-desktops 1 2 3 4 5 6 7 8 9

polybar example
