#! /bin/sh

sxhkd &

# ~/.startscript.sh

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc monitor -d 1 2 3 4 5 6 7 8 9

~/.config/polybar/launch.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
# bspc config gapless_monocle      true
bspc config single_monocle true
bspc config gapless_monocle false

# super/win mouse to move/resize
bspc config pointer_modifier mod4
bspc config focus_follows_pointer true

# Always use the last WM_CLASS from the sequence
# if there are 2 values the first one refers to the instance
# while the second value refers to the class
bspc rule -a Chromium desktop='^1' follow=on
bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a Emacs state=tiled desktop='^2' follow=on
bspc rule -a jetbrains-idea desktop='^2' follow=off
# bspc rule -a Bitwarden state=floating desktop='^9' follow=on center=true rectangle=1340x720+0+0
# High DPI
bspc rule -a Bitwarden state=floating desktop='^9' follow=on center=true rectangle=2122x1106+0+0

bspc rule -a mpv state=floating follow=on center=true rectangle=1280x720+0+0
bspc rule -a Logseq desktop='^5' state=fullscreen
bspc rule -a gpclient state=floating desktop='^9' follow=off rectangle=680x1206+0+68
bspc rule -a Google-chrome:calendar.google.com__calendar_render desktop='^5' follow=off
bspc rule -a thunderbird desktop='^5' follow=off
bspc rule -a Slack desktop='^5' follow=off
bspc rule -a Emacs:orgmacs state=tiled desktop='^5' follow=off


sidebarw=1040

# locked=on if it should not be closeable
bspc rule -a scratchterm border=off sticky=on state=floating hidden=off locked=off rectangle=$(xdpyinfo  | grep -oP 'dimensions:\s+\K[0-9]+')x533+0+0


bspc rule -a Alacritty:scratchterm border=off sticky=on state=floating hidden=off locked=off rectangle=$(xdpyinfo  | grep -oP 'dimensions:\s+\K[0-9]+')x533+0+0

bspc rule -a Emacs:scratchmacs border=off sticky=on state=floating hidden=off locked=off rectangle=${sidebarw}x$(xdpyinfo  | grep -oP 'dimensions:\s+[0-9]*x\K[0-9]+')+$(($(xdpyinfo  | grep -oP 'dimensions:\s+\K[0-9]+') - $sidebarw))+0

bspc rule -a scratchbrowser border=off sticky=on state=floating hidden=off locked=off rectangle=${sidebarw}x$(xdpyinfo  | grep -oP 'dimensions:\s+[0-9]*x\K[0-9]+')+$(($(xdpyinfo  | grep -oP 'dimensions:\s+\K[0-9]+') - $sidebarw))+0

bspc rule -a qutebrowser:scratchbrowser border=off sticky=on state=floating hidden=off locked=off rectangle=${sidebarw}x$(xdpyinfo  | grep -oP 'dimensions:\s+[0-9]*x\K[0-9]+')+$(($(xdpyinfo  | grep -oP 'dimensions:\s+\K[0-9]+') - $sidebarw))+0

#bspc monitor --reset-desktops 1 2 3 4 5 6 7 8 9
