#! /bin/sh

sxhkd &

~/.startscript.sh

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc monitor -d 1 2 3 4 5 6 7 8 9

~/.config/polybar/launch.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# super/win mouse to move/resize
bspc config pointer_modifier mod4

# Always use the last WM_CLASS from the sequence
# if there are 2 values the first one refers to the instance
# while the second value refers to the class
bspc rule -a Chromium desktop='^1' follow=on
bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a Emacs state=tiled desktop='^2' follow=on

#bspc monitor --reset-desktops 1 2 3 4 5 6 7 8 9
